# Generated by Django 6.0.3 on 2026-03-31 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('potential', 'Potential'), ('applied', 'Applied')], default='potential', max_length=20)),
                ('snippet', models.TextField(blank=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('visited', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.visited')),
            ],
        ),
        migrations.CreateModel(
            name='RankedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('html', models.TextField()),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'indexes': [models.Index(fields=['score'], name='jobs_ranked_score_8a1dbb_idx')],
            },
        ),
    ]
