# Generated by Django 6.0.3 on 2026-03-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employer_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tracker_url',
            field=models.URLField(blank=True),
        ),
    ]
