# Generated by Django 6.0.3 on 2026-03-31 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_employer_url_job_tracker_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tracker_url',
        ),
    ]
