# Generated by Django 6.0.3 on 2026-04-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_tracker_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('potential', 'Potential'), ('applied', 'Applied'), ('ranked', 'Ranked')], default='potential', max_length=20),
        ),
    ]
